name: app

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18" 

            - name: Install dependencies
              working-directory: ./app
              run: npm install

            - name: Lint the code
              working-directory: ./app
              run: npm run lint

            - name: Build the Expo app
              working-directory: ./app
              run: expo build:android -t apk
