name: Contract CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and Check Contract in ./contract

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Aiken
              uses: aiken-lang/setup-aiken@v1
              with:
                  version: v1.1.0

            - name: Format Check
              working-directory: ./contract
              run: aiken fmt --check

            - name: Lint and Type Check
              working-directory: ./contract
              run: aiken check -D

            - name: Build Contract
              working-directory: ./contract
              run: aiken build

