name: server

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - "*"

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18" 

            - name: Install dependencies
              working-directory: ./server
              run: npm install

            - name: Run tests
              working-directory: ./server
              run: npm run test 

            - name: Linting
              working-directory: ./server
              run: npm run lint

            - name: Build the project
              working-directory: ./server
              run: npm run build

